"""Generate frozen Skyfield references without importing AstroScope, Astropy or ERFA.

Run explicitly with reference-requirements.txt installed; never regenerated by CI.
"""

from __future__ import annotations

import hashlib
import importlib.metadata
import json
import math
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

import numpy as np
from skyfield.api import Star, load, load_file, wgs84
from skyfield_data import get_skyfield_data_path

ROOT = Path(__file__).resolve().parents[2]
EOP = ROOT / "validation/fixtures/celestial_eop_v1.json"
FIXTURE = ROOT / "validation/fixtures/celestial_coordinates_v1.json"
MANIFEST = ROOT / "validation/manifests/celestial_coordinates_v1.json"
SITES = [
    ("tokyo", 35.6762, 139.6503, 40),
    ("greenwich", 51.4769, 0.0005, 46),
    ("paranal", -24.6272, -70.4042, 2635),
    ("equator", 0, 30, 0),
    ("arctic", 78.2232, 15.6469, 20),
    ("antarctic", -75.1, 123.35, 3233),
    ("dateline_east", 10, 179.999, 100),
    ("dateline_west", -10, -179.999, 100),
]
DATES = ["2024-03-20", "2024-06-21", "2024-09-22", "2024-12-21"]
TIMES = ["00:00:00", "06:15:30.500000", "23:59:59.500000"]
TARGETS = [(0.0001, 0), (23.9999, -30), (6, 45), (12, -60), (18, 89.9), (3, -89.9)]


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def coordinate_strings(ra: float, dec: float, style: int) -> tuple[str, str]:
    """Format independently, preserving coordinates to far better than a milliarcsecond."""
    if style == 0:
        return f"{ra:.15f}h", f"{dec:+.15f}d"
    if style == 1:
        return f"  {ra:.15f}  ", f"  {dec:+.15f}  "
    hour, minute = int(ra), int((ra % 1) * 60)
    sec = (ra * 3600) % 60
    degree, arcmin = int(abs(dec)), int((abs(dec) % 1) * 60)
    arcsec = (abs(dec) * 3600) % 60
    return (
        f"{hour:02}:{minute:02}:{sec:015.12f}",
        f"{'-' if dec < 0 else '+'}{degree:02}:{arcmin:02}:{arcsec:015.12f}",
    )


def generate() -> None:
    rows = json.loads(EOP.read_text())["rows"]
    mjds = np.array([r["MJD"] for r in rows])
    kernel = Path(get_skyfield_data_path()) / "de421.bsp"
    eph = load_file(str(kernel))
    cases: list[dict[str, Any]] = []
    for day in DATES:
        instants = [datetime.fromisoformat(f"{day}T{clock}+00:00") for clock in TIMES]
        instants.append(instants[0] + timedelta(days=1, microseconds=500000))
        for time_index, dt in enumerate(instants):
            mjd = 40587 + (dt - datetime(1970, 1, 1, tzinfo=UTC)).total_seconds() / 86400
            lower = math.floor(mjd)
            if lower not in mjds or lower + 1 not in mjds:
                raise ValueError("EOP must bracket every instant with consecutive daily rows")
            eop = {
                k: float(np.interp(mjd, mjds, [r[k] for r in rows]))
                for k in ["UT1_UTC", "PM_x", "PM_y"]
            }
            ts = load.timescale(builtin=True, delta_t=69.184 - eop["UT1_UTC"])
            t = ts.from_datetime(dt)
            ts.polar_motion_table = (
                np.array([t.tt - 1, t.tt + 1]),
                np.array([eop["PM_x"]] * 2),
                np.array([eop["PM_y"]] * 2),
            )
            for name, lat, lon, height in SITES:
                if time_index == 3 and not name.startswith("dateline"):
                    continue
                site = wgs84.latlon(lat, lon, elevation_m=height)
                observer = (eph["earth"] + site).at(t)

                def position(ra: float, dec: float, observer=observer) -> tuple[float, float]:
                    a, z, _ = (
                        observer.observe(Star(ra_hours=ra, dec_degrees=dec)).apparent().altaz()
                    )
                    return float(a.degrees), float(z.degrees)

                targets = [(ra, dec, "grid") for ra, dec in TARGETS]
                if time_index == 3:
                    targets = [(TARGETS[0][0], TARGETS[0][1], "utc_date_boundary")]
                centre = float((t.gast + lon / 15) % 24)
                if time_index == 0:
                    targets.extend(
                        ((centre + delta) % 24, lat + 10, "near_culmination")
                        for delta in [-0.03, 0, 0.03]
                    )
                if name == "equator":
                    altitudes = [-0.1, 0.1, 4.9, 5.1, 19.9, 20.1, 89.5]
                    if time_index == 0:
                        altitudes.append(0.0)
                    for altitude in altitudes:
                        lo, hi = centre, centre + 8
                        for _ in range(60):
                            mid = (lo + hi) / 2
                            if position(mid % 24, 0)[0] > altitude:
                                lo = mid
                            else:
                                hi = mid
                        targets.append(((lo + hi) / 2 % 24, 0, f"boundary_{altitude}"))
                for index, (ra, dec, category) in enumerate(targets):
                    alt, az = position(ra, dec)
                    ra_input, dec_input = coordinate_strings(ra, dec, index % 3)
                    cases.append(
                        {
                            "id": f"{name}_{day}_{time_index}_{index:02}",
                            "category": category,
                            "site": name,
                            "latitude_deg": lat,
                            "longitude_deg": lon,
                            "elevation_m": height,
                            "utc": dt.isoformat(),
                            "ra_hours": ra,
                            "dec_degrees": dec,
                            "right_ascension": ra_input,
                            "declination": dec_input,
                            "eop": eop,
                            "expected": {
                                "observer_xyz_m": [float(v) for v in site.itrs_xyz.m],
                                "altitude_deg": alt,
                                "azimuth_deg": az,
                                "lst_hours": centre,
                                "jd_utc": mjd + 2400000.5,
                                "mjd_utc": mjd,
                                "above_horizon": alt > 0,
                                "secz": 1 / math.sin(math.radians(alt)) if alt >= 5 else None,
                            },
                        }
                    )
    invalid = [
        {"id": key, "field": field, "value": value, "error": "ValueError"}
        for key, field, value in [
            ("negative_ra", "right_ascension", "-1h"),
            ("ra_24h", "right_ascension", "24h"),
            ("ra_nonfinite", "right_ascension", "nan"),
            ("ra_malformed", "right_ascension", "not-a-coordinate"),
            ("dec_high", "declination", "+90.1d"),
            ("dec_low", "declination", "-90.1d"),
            ("dec_nonfinite", "declination", "nan"),
            ("latitude_high", "latitude_deg", 90.1),
            ("latitude_low", "latitude_deg", -90.1),
            ("longitude_high", "longitude_deg", 180.1),
            ("longitude_low", "longitude_deg", -180.1),
            ("elevation_high", "elevation_m", 10001),
            ("elevation_low", "elevation_m", -501),
        ]
    ]
    fixture = {
        "schema_version": "1.0",
        "reference": {
            "engine": "Skyfield",
            "versions": {
                p: importlib.metadata.version(p)
                for p in ["skyfield", "skyfield-data", "numpy", "jplephem", "sgp4"]
            },
            "kernel": "de421.bsp",
            "kernel_sha256": sha(kernel),
            "kernel_source": "https://ssd.jpl.nasa.gov/ftp/eph/planets/bsp/de421.bsp",
            "eop_sha256": sha(EOP),
            "generator_sha256": sha(Path(__file__)),
            "frame": "ICRS fixed stars; zero proper motion/parallax/radial velocity",
            "site_datum": "WGS84",
            "refraction": "disabled",
            "azimuth": "degrees east from north",
            "time": "UTC in 2024; TAI-UTC=37s; daily DUT1 and polar motion interpolated linearly",
            "independence": "Skyfield versus Astropy/ERFA; shared IERS observations",
            "input_rejection_reference": "Documented public range contracts, not Skyfield results",
            "precision": "float64; decimal coordinates 15 places, sexagesimal seconds 12 places",
        },
        "cases": cases,
        "invalid_inputs": invalid,
    }
    FIXTURE.write_text(json.dumps(fixture, indent=2, allow_nan=False) + "\n")
    manifest = {
        "schema_version": "1.0",
        "benchmark_id": "celestial-coordinates-v1",
        "expected_case_count": len(cases),
        "expected_invalid_input_count": len(invalid),
        "files": {str(p.relative_to(ROOT)): sha(p) for p in [FIXTURE, EOP]},
        "tolerances": {
            "observer_metres": 1e-6,
            "altitude_arcsec": 2.0,
            "direction_arcsec": 2.0,
            "azimuth_arcsec": 10.0,
            "lst_seconds": 0.05,
            "jd_seconds": 0.0001,
            "mjd_seconds": 0.0001,
            "ra_input_arcsec": 1e-7,
            "dec_input_arcsec": 1e-7,
            "airmass_relative": 5e-5,
            "low_altitude_secz_relative": 2e-4,
        },
        "azimuth_component_excluded_above_abs_altitude_deg": 89.0,
        "horizon_ambiguity_arcsec": 2.0,
        "airmass_scientific_minimum_altitude_deg": 20.0,
        "airmass_policy_minimum_altitude_deg": 5.0,
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"Generated {len(cases)} scientific cases and {len(invalid)} input contracts")


if __name__ == "__main__":
    generate()
